### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by qwerty2501** [TaKO8Ki/testfixtures#32]
Hello.
It's a interesting idea.
However, It seems is updated last 3 year's ago.
Do you intend to continue maintaining this repository?

**Comment by TaKO8Ki** [comment]
@qwerty2501 Hi. Thank you for the message. If someone want to use this library now, I will start maintaining testfixtures. However it takes some time, so if you need it right away, I think it's best to fork the repository and maintain it yourself. For starters, I suggest updating the versions of SQLx and the async runtime to the latest.

**Comment by qwerty2501** [comment]
@TaKO8Ki Thank you for the response.
I don't need it right away. And I just find it interesting.
I haven't decided yet, however I might fork it. (And I might publish to crates.io as another name crate, if I succeeded.)
